# Generated by Django 3.1.6 on 2021-02-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='corporation',
            table='corporation',
        ),
    ]
