# Generated by Django 3.1.6 on 2021-03-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corporate_name', models.CharField(max_length=255)),
                ('corporate_code', models.CharField(max_length=255)),
                ('consolidation', models.CharField(max_length=255)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
    ]
