# Generated by Django 3.1.6 on 2021-03-09 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='User.email', to='user.user'),
        ),
    ]
